const CONFIG = { 
introTitle: 'alo alo,trịnh linh ngu 😂',
introDesc:`biết t định làm gì k ??`,
btnIntro: 'đíu biết',
title: 'đíu nói làm sao mà bít đc hehe😒',
desc: 'm bị ngáo 🤣 ',
btnYes: 'ủa sao biết hay z',
btnNo: 'dmm ngáo ý',
question:'t biết m đang rất muốn chửi t nên là phần chat này là của m :))',
btnReply: 'thoải mái đê <3',
reply: 't bị thiểu năng nha m k ngáo tí nào <33333333', 
mess: 'linh thúi thúi ', 
messDesc: 'sn tặng m cái này này 💩💩.', 
btnAccept: 'hahaha <3',
}
