const CONFIG = { 
introTitle: 'alo alo ,b iu à', 
introDesc:'biết t định làm gì k ??? ',
btnIntro: 'đíu biết', 
title: 'đíu nói làm sao mà bít đc hehe 😙', 
desc: 'tui có nên chúc tử tế k ta ?? ', 
btnYes: 'tất nhiên là k rồi <33', 
btnNo: 'có nha tr:3', 
question:'t bt là m đang rất muốn chửi t thế là t đã để nguyên cái phần chat cho m <3', 
btnReply: 'thoải mái đê <3', 
reply: 'CHÚC MỪNG SINH NHẬT NHA <33333333', 
mess: 'tuổi mới ngày càng xinh đẹp và luôn vui vẻ nha 🥰. ntl mọi điều tuyệt vời nhất sẽ đến bên m 😘😘', 
messDesc: 'đừng buồn nữa nha,cảm ơn m nhìu nhìu thời gian qua.', 
btnAccept: 'hahaha <3',
